### ISSUE TITLE
一个页面中有多个网络请求，请求失败后根据业务逻辑分别判断，请问如何判断？

### ISSUE THREAD

**Issue by hystrixis** [laishujie/ComicMTC_v2#1]
举个例子，以下代码是无法区分来自哪个api请求的，如果要区分，如何区分呢，，最近刚学这个，还不太了解，求大神解答
`inline fun <reified VM : BaseViewModel> createViewModel(): VM {
        val mViewModel = ViewModelProvider(this)[VM::class.java]
        mViewModel.mException.observe(this, Observer {
            hideLoading()
            toastMessage(it)
        })
        return mViewModel
    }`

**Comment by laishujie** [comment]
> 举个例子，以下代码是无法区分来自哪个api请求的，如果要区分，如何区分呢，，最近刚学这个，还不太了解，求大神解答
> `inline fun <reified VM : BaseViewModel> createViewModel(): VM { val mViewModel = ViewModelProvider(this)[VM::class.java] mViewModel.mException.observe(this, Observer { hideLoading() toastMessage(it) }) return mViewModel }`

这个只是全局错误处理。如果想区分的话。BaseViewModel有个方法
```
 fun <T> runOnIo(
 request: suspend CoroutineScope.() -> ComicResponse<T>,
 success: ((info: ComicResponse.DataBean<T>) -> Unit), 
 error: ((info: ComicResponse<T>) -> Unit) ){

}
```

里面有失败和错误的回调 。
