### ISSUE TITLE
请问大佬,接口都是怎么获取的

### ISSUE THREAD

**Issue by 390057892** [laishujie/ComicMTC_v2#6]
问下大佬,你做开源项目接口怎么获取的啊，用charles抓的么。。

**Comment by dengdailk** [comment]
你好，&nbsp; &nbsp; &nbsp;我获取接口的方式有一下几点，希望对你有所帮助，我是做android的
&nbsp; &nbsp; &nbsp;1.网上搜索公共公开的api接口，自己测试下能不能用，有的会过期不能用
&nbsp; &nbsp; &nbsp;2.看别人写的app源码，从中不仅可以找到api，还可以学习别人程序的写法，架构之类的东西，还可以学习别人对接口的处理方式。
&nbsp; &nbsp; &nbsp;3.github上也有一些App源码，可以自己跑一下
&nbsp; &nbsp; &nbsp;4.www.wanandroid.com有一套完整的api接口，和一些大佬用各种语言和方式开发的玩Android客户端app,可以参考学习下
&nbsp; &nbsp; &nbsp;希望对你有帮助

**Comment by laishujie** [comment]
> 问下大佬,你做开源项目接口怎么获取的啊，用charles抓的么。。

如果只是学习，最好选择公开的接口，稳定，比如玩Android平台提供的接口，如果只想要做特定内容模块，比如漫画动画啥一般都是两种方式。

**Comment by laishujie** [comment]
> 问下大佬,你做开源项目接口怎么获取的啊，用charles抓的么。。

如果单单只是学习，去玩Android这种网站找提供稳定的API就好了，如果是想要做特定的内容，比如动画/漫画啥的。要么就是寻找 类似的开源项目/付费api(比如聚合数据)，要么抓包获取接口，要么通过爬虫（jsoup这种）爬取网页生成数据。
